---
title: "Education and travel: DID"
---

```{r load packages}
library(dplyr)
library(tidyr)
```


```{r load imputed data}
#clear environment
rm(list=ls())

#load imputed data
setwd("~/Box Sync/education and travel/R")
load("~/Box Sync/education and travel/R/data_knn.RData")
#summary(data.knn)

#delete imputation information variables
data_cs <- data.knn[1:62]
summary(data_cs)
dim(data_cs)
```


```{r change values}
#change Female = 0
levels(data_cs$GENDER)[levels(data_cs$GENDER)=="2"] <- "0"
summary(data_cs$GENDER)

#create race dummies
data_cs$white <- ifelse(data_cs$RACE==1, 1, 0)
data_cs$asian <- ifelse(data_cs$RACE==5, 1, 0)
data_cs$black <- ifelse(data_cs$RACE==2, 1, 0)
data_cs$hispanic <- ifelse(data_cs$RACE==3, 1, 0)
summary(data_cs$white)
summary(data_cs$black)
summary(data_cs$asian)
summary(data_cs$hispanic)

#format non-english speaking (does not speak english at home - 0, enlgish at home - 1)
levels(data_cs$C1SCREEN)[levels(data_cs$C1SCREEN)=="1"] <- "0"
levels(data_cs$C1SCREEN)[levels(data_cs$C1SCREEN)=="2"] <- "1"
summary(data_cs$C1SCREEN)
levels(data_cs$C1SCREEN)

levels(data_cs$C2SCREEN)[levels(data_cs$C2SCREEN)=="1"] <- "0"
levels(data_cs$C2SCREEN)[levels(data_cs$C2SCREEN)=="2"] <- "1"

levels(data_cs$C5SCREEN)[levels(data_cs$C5SCREEN)=="1"] <- "0"
levels(data_cs$C5SCREEN)[levels(data_cs$C5SCREEN)=="2"] <- "1"

#expectation level to years of education
summary(data_cs$P1EXPECT)
levels(data_cs$P1EXPECT)[levels(data_cs$P1EXPECT)=="6"] = "22"
levels(data_cs$P1EXPECT)[levels(data_cs$P1EXPECT)=="5"] = "18"
levels(data_cs$P1EXPECT)[levels(data_cs$P1EXPECT)=="4"] = "16"
levels(data_cs$P1EXPECT)[levels(data_cs$P1EXPECT)=="3"] = "14"
levels(data_cs$P1EXPECT)[levels(data_cs$P1EXPECT)=="2"] = "12"
levels(data_cs$P1EXPECT)[levels(data_cs$P1EXPECT)=="1"] = "8"
data_cs$P1EXPECT <- as.numeric(levels(data_cs$P1EXPECT))[data_cs$P1EXPECT]
summary(data_cs$P1EXPECT)

levels(data_cs$P5EXPECT)[levels(data_cs$P5EXPECT)=="6"] = "22"
levels(data_cs$P5EXPECT)[levels(data_cs$P5EXPECT)=="5"] = "18"
levels(data_cs$P5EXPECT)[levels(data_cs$P5EXPECT)=="4"] = "16"
levels(data_cs$P5EXPECT)[levels(data_cs$P5EXPECT)=="3"] = "14"
levels(data_cs$P5EXPECT)[levels(data_cs$P5EXPECT)=="2"] = "12"
levels(data_cs$P5EXPECT)[levels(data_cs$P5EXPECT)=="1"] = "8"
data_cs$P5EXPECT <- as.numeric(levels(data_cs$P5EXPECT))[data_cs$P5EXPECT]
summary(data_cs$P5EXPECT)

#change travel variables to dummy variables
levels(data_cs$P2CONCRT)[levels(data_cs$P2CONCRT)=="2"] <- "0"
levels(data_cs$P2MUSEUM)[levels(data_cs$P2MUSEUM)=="2"] <- "0"
levels(data_cs$P2ZOO)[levels(data_cs$P2ZOO)=="2"] <- "0"
levels(data_cs$P2SPORT)[levels(data_cs$P2SPORT)=="2"] <- "0"

levels(data_cs$P5CONCRT)[levels(data_cs$P5CONCRT)=="2"] <- "0"
levels(data_cs$P5MUSEUM)[levels(data_cs$P5MUSEUM)=="2"] <- "0"
levels(data_cs$P5ZOO)[levels(data_cs$P5ZOO)=="2"] <- "0"
levels(data_cs$P5SPTEVT)[levels(data_cs$P5SPTEVT)=="2"] <- "0"


#parent's educational status to years of education
levels(data_cs$WKMOMED)[levels(data_cs$WKMOMED)=="9"] = "22"
levels(data_cs$WKMOMED)[levels(data_cs$WKMOMED)=="8"] = "18"
levels(data_cs$WKMOMED)[levels(data_cs$WKMOMED)=="7"] = "18"
levels(data_cs$WKMOMED)[levels(data_cs$WKMOMED)=="6"] = "16"
levels(data_cs$WKMOMED)[levels(data_cs$WKMOMED)=="5"] = "14"
levels(data_cs$WKMOMED)[levels(data_cs$WKMOMED)=="4"] = "14"
levels(data_cs$WKMOMED)[levels(data_cs$WKMOMED)=="3"] = "12"
levels(data_cs$WKMOMED)[levels(data_cs$WKMOMED)=="2"] = "12"
levels(data_cs$WKMOMED)[levels(data_cs$WKMOMED)=="1"] = "8"
data_cs$WKMOMED <- as.numeric(levels(data_cs$WKMOMED))[data_cs$WKMOMED]
summary(data_cs$WKMOMED)

levels(data_cs$WKDADED)[levels(data_cs$WKDADED)=="9"] = "22"
levels(data_cs$WKDADED)[levels(data_cs$WKDADED)=="8"] = "18"
levels(data_cs$WKDADED)[levels(data_cs$WKDADED)=="7"] = "18"
levels(data_cs$WKDADED)[levels(data_cs$WKDADED)=="6"] = "16"
levels(data_cs$WKDADED)[levels(data_cs$WKDADED)=="5"] = "14"
levels(data_cs$WKDADED)[levels(data_cs$WKDADED)=="4"] = "14"
levels(data_cs$WKDADED)[levels(data_cs$WKDADED)=="3"] = "12"
levels(data_cs$WKDADED)[levels(data_cs$WKDADED)=="2"] = "12"
levels(data_cs$WKDADED)[levels(data_cs$WKDADED)=="1"] = "8"
data_cs$WKDADED <- as.numeric(levels(data_cs$WKDADED))[data_cs$WKDADED]
summary(data_cs$WKDADED)

levels(data_cs$W1MOMED)[levels(data_cs$W1MOMED)=="9"] = "22"
levels(data_cs$W1MOMED)[levels(data_cs$W1MOMED)=="8"] = "18"
levels(data_cs$W1MOMED)[levels(data_cs$W1MOMED)=="7"] = "18"
levels(data_cs$W1MOMED)[levels(data_cs$W1MOMED)=="6"] = "16"
levels(data_cs$W1MOMED)[levels(data_cs$W1MOMED)=="5"] = "14"
levels(data_cs$W1MOMED)[levels(data_cs$W1MOMED)=="4"] = "14"
levels(data_cs$W1MOMED)[levels(data_cs$W1MOMED)=="3"] = "12"
levels(data_cs$W1MOMED)[levels(data_cs$W1MOMED)=="2"] = "12"
levels(data_cs$W1MOMED)[levels(data_cs$W1MOMED)=="1"] = "8"
data_cs$W1MOMED <- as.numeric(levels(data_cs$W1MOMED))[data_cs$W1MOMED]
summary(data_cs$W1MOMED)

levels(data_cs$W1DADED)[levels(data_cs$W1DADED)=="9"] = "22"
levels(data_cs$W1DADED)[levels(data_cs$W1DADED)=="8"] = "18"
levels(data_cs$W1DADED)[levels(data_cs$W1DADED)=="7"] = "18"
levels(data_cs$W1DADED)[levels(data_cs$W1DADED)=="6"] = "16"
levels(data_cs$W1DADED)[levels(data_cs$W1DADED)=="5"] = "14"
levels(data_cs$W1DADED)[levels(data_cs$W1DADED)=="4"] = "14"
levels(data_cs$W1DADED)[levels(data_cs$W1DADED)=="3"] = "12"
levels(data_cs$W1DADED)[levels(data_cs$W1DADED)=="2"] = "12"
levels(data_cs$W1DADED)[levels(data_cs$W1DADED)=="1"] = "8"
data_cs$W1DADED <- as.numeric(levels(data_cs$W1DADED))[data_cs$W1DADED]
summary(data_cs$W1DADED)

levels(data_cs$W5MOMED)[levels(data_cs$W5MOMED)=="9"] = "22"
levels(data_cs$W5MOMED)[levels(data_cs$W5MOMED)=="8"] = "18"
levels(data_cs$W5MOMED)[levels(data_cs$W5MOMED)=="7"] = "18"
levels(data_cs$W5MOMED)[levels(data_cs$W5MOMED)=="6"] = "16"
levels(data_cs$W5MOMED)[levels(data_cs$W5MOMED)=="5"] = "14"
levels(data_cs$W5MOMED)[levels(data_cs$W5MOMED)=="4"] = "14"
levels(data_cs$W5MOMED)[levels(data_cs$W5MOMED)=="3"] = "12"
levels(data_cs$W5MOMED)[levels(data_cs$W5MOMED)=="2"] = "12"
levels(data_cs$W5MOMED)[levels(data_cs$W5MOMED)=="1"] = "8"
data_cs$W5MOMED <- as.numeric(levels(data_cs$W5MOMED))[data_cs$W5MOMED]
summary(data_cs$W5MOMED)

levels(data_cs$W5DADED)[levels(data_cs$W5DADED)=="9"] = "22"
levels(data_cs$W5DADED)[levels(data_cs$W5DADED)=="8"] = "18"
levels(data_cs$W5DADED)[levels(data_cs$W5DADED)=="7"] = "18"
levels(data_cs$W5DADED)[levels(data_cs$W5DADED)=="6"] = "16"
levels(data_cs$W5DADED)[levels(data_cs$W5DADED)=="5"] = "14"
levels(data_cs$W5DADED)[levels(data_cs$W5DADED)=="4"] = "14"
levels(data_cs$W5DADED)[levels(data_cs$W5DADED)=="3"] = "12"
levels(data_cs$W5DADED)[levels(data_cs$W5DADED)=="2"] = "12"
levels(data_cs$W5DADED)[levels(data_cs$W5DADED)=="1"] = "8"
data_cs$W5DADED <- as.numeric(levels(data_cs$W5DADED))[data_cs$W5DADED]
summary(data_cs$W5DADED)
```

```{r turn data into panel}
#change the data into panel format
#which(colnames(data_cs)=="P5SPORT")
#which(colnames(data_cs)=="P5SPTEVT")
#which(colnames(data_cs)=="P1SPORT")
#which(colnames(data_cs)=="WKMOMED")

#change the column names to avoid confusion
colnames(data_cs)[43] <- "P1SPRTS"
colnames(data_cs)[56] <- "P5SPRTS"
colnames(data_cs)[61] <- "P5SPORT"

colnames(data_cs)[18] <- "W0MOMED"
colnames(data_cs)[19] <- "W0DADED"
colnames(data_cs)[20] <- "W0MOMSCR"
colnames(data_cs)[21] <- "W0DADSCR"
colnames(data_cs)[22] <- "W0INCOME"
colnames(data_cs)

#change to panel format
data_rs <- reshape(data = data_cs, 
                   idvar = "CHILDID", 
                   varying = c("C1R4RSCL", 	 "C1R4MSCL", "C2R4RSCL", 	"C2R4MSCL", 	"C5R4RSCL", 	"C5R4MSCL", 	"T1LEARN", 	"T2LEARN", 	"T4LEARN", 	"T5LEARN", 	"W0MOMED", "W0DADED", 	"W0MOMSCR", 	"W0DADSCR", 	"W0INCOME", 	"W1MOMED", 	"W1DADED", 	"W1MOMSCR", 	"W1DADSCR", 	"W1INCOME", "W5MOMED", 	"W5DADED", 	"W5MOMSCR", 	"W5DADSCR", 	"C1SCREEN", 	"C2SCREEN", 	"C5SCREEN", 	"P1EXPECT", 	"P1READBO", "P1TELLST", 	"P1SINGSO", 	"P1HELPAR", 	"P1GAMES", 	"P1NATURE", 	"P1BUILD", 	"P1SPRTS", 	"P2CONCRT", 	"P2MUSEUM", "P2ZOO", 	"P2SPORT", 	"P2INCOME", 	"P5EXPECT", 	"P5TELLST", 	"P5SINGSO", 	"P5HELPAR", 	"P5GAMES", 	"P5NATURE", "P5BUILD", 	"P5SPRTS", 	"P5READBO", 	"P5CONCRT", 	"P5MUSEUM", 	"P5ZOO", 	"P5SPORT", 	"P5TINCTH"), 
                   v.names = "value",
                   timevar = "period", 
                   times = c("C1R4RSCL", 	 "C1R4MSCL", "C2R4RSCL", 	"C2R4MSCL", 	"C5R4RSCL", 	"C5R4MSCL", 	"T1LEARN", 	"T2LEARN", 	"T4LEARN", 	"T5LEARN", 	"W0MOMED", "W0DADED", 	"W0MOMSCR", 	"W0DADSCR", 	"W0INCOME", 	"W1MOMED", 	"W1DADED", 	"W1MOMSCR", 	"W1DADSCR", 	"W1INCOME", "W5MOMED", 	"W5DADED", 	"W5MOMSCR", 	"W5DADSCR", 	"C1SCREEN", 	"C2SCREEN", 	"C5SCREEN", 	"P1EXPECT", 	"P1READBO", "P1TELLST", 	"P1SINGSO", 	"P1HELPAR", 	"P1GAMES", 	"P1NATURE", 	"P1BUILD", 	"P1SPRTS", 	"P2CONCRT", 	"P2MUSEUM", "P2ZOO", 	"P2SPORT", 	"P2INCOME", 	"P5EXPECT", 	"P5TELLST", 	"P5SINGSO", 	"P5HELPAR", 	"P5GAMES", 	"P5NATURE", "P5BUILD", 	"P5SPRTS", 	"P5READBO", 	"P5CONCRT", 	"P5MUSEUM", 	"P5ZOO", 	"P5SPORT", 	"P5TINCTH"), 
                   direction = "long")

data_rs <- data_rs %>% 
  separate(col = period, into= c("round", "variable"), sep = 2, remove = TRUE,
  convert = FALSE, extra = "warn", fill = "warn") %>%
  distinct()

data_rs$round <- gsub("[a-zA-Z ]", "", data_rs$round)
#data_rs$variable <- substring(data_rs$variable, 3)
```

```{r wide format}
data_wide <- spread(data_rs, variable, value)
data_wide[8:35] <- lapply(data_wide[8:35], as.numeric)
dim(data_wide)
```

```{r}
data <- data_wide[!is.na(data_wide$CHILDID),]
data <- distinct(data)
dim(data)

#reorder the columns
tripCols <- c("CHILDID", "PARENTID", "S1_ID", "CREGION", "DOBYY", "GENDER", "RACE", "CONCRT", "MUSEUM", "ZOO", "SPORT")
data <- data[, c(tripCols, setdiff(names(data), tripCols))]

#change negative values to 0 for trip variables and NA for the other variables
summary(data[8:11])
data[8:11] <- as.data.frame(lapply(data[8:11], function(x) ifelse(x < 0, 0, x)))
summary(data[8:11])

data[12:35] <- as.data.frame(lapply(data[12:35], function(x) ifelse(x < 0, NA, x)))
#summary(data[12:35])

#create trip variable - sum of four trip variables
data$trip <- rowSums(data[8:11], na.rm = FALSE)
summary(data$trip)

#create time spent with children- sum of nine variables
twcCols <- c("BUILD", "GAMES", "HELPAR", "NATURE", "READBO", "SINGSO", "SPRTS", "TELLST")
data <- data[, c(setdiff(names(data), twcCols), twcCols)]
summary(data[29:36])

data$timeWchildren <- rowSums(data[29:36], na.rm = TRUE)
data$timeWchildren <- ifelse(data$timeWchildren==0, NA, data$timeWchildren)
summary(data$timeWchildren)
```

```{r create did variables}
#create time variable
data$time = ifelse(data$round > 2, 1, 0)

#create treated variable - if took at least one trip, 1, else 0
data$treated = ifelse(data$trip[data$round==2] > 0, 1, 0)
data$treatedM = ifelse(data$MUSEUM[data$round==2] > 0, 1, 0)
data$treatedS = ifelse(data$SPORT[data$round==2] > 0, 1, 0)
data$treatedC = ifelse(data$CONCRT[data$round==2] > 0, 1, 0)
data$treatedZ = ifelse(data$ZOO[data$round==2] > 0, 1, 0)

#create did variable - an interaction between time and treated
data$did = data$time * data$treated
data$didM = data$time * data$treatedM
data$didS = data$time * data$treatedS
data$didC = data$time * data$treatedC
data$didZ = data$time * data$treatedZ
```

```{r}
data$math5 <- data$R4MSCL[data$round==5]
data$reading5 <- data$R4RSCL[data$round==5]

boxplot(math5~trip, data=data, main=toupper(""), font.main=3, cex.main=1.2, xlab="Number of trips", ylab="Math Score", font.lab=3, col="darkgreen")

boxplot(reading5~CONCRT, data=data, main=toupper(""), font.main=3, cex.main=1.2, col=c("red","blue", "yellow", "green"), xlab="Number of trips", ylab="Reading Score", font.lab=3, notch=TRUE, range = 0)
```


```{r did regression}
#propensity score matching
#install.packages("MatchIt")
library(MatchIt)

m.out = matchit(reading5 ~ EXPECT + LEARN + timeWchildren + DADED + DADSCR + MOMED + MOMSCR + SCREEN + TINCTH, data = data, method = "nearest", ratio = 1)


summary(m.out)
plot(m.out, type = "jitter")
plot(m.out, type = "hist")

didreg <- lm(R4MSCL ~ treated*time + EXPECT + LEARN + timeWchildren + DADED + DADSCR + MOMED + MOMSCR + SCREEN + TINCTH + white + black + asian, data = data)
summary(didreg)


xvar <- c(trip )

```


